In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"Dataset/survey_results_public.csv")
df

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,NaN,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88878,88377,NaN,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,"Not employed, and not looking for work",Canada,No,Primary/elementary school,NaN,...,NaN,Tech articles written by other developers;Tech...,NaN,Man,No,NaN,NaN,No,Appropriate in length,Easy
88879,88601,NaN,No,Never,The quality of OSS and closed source software ...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88880,88802,NaN,No,Never,NaN,Employed full-time,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88881,88816,NaN,No,Never,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88882,88863,NaN,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, and not looking for work",Spain,"Yes, full-time","Professional degree (JD, MD, etc.)","Computer science, computer engineering, or sof...",...,Somewhat less welcome now than last year,Tech articles written by other developers;Indu...,18.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;White or of European...,No,Appropriate in length,Easy

In [3]:
india = df[df["Country"]=="India"]
india

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
7,8,I code primarily as a hobby,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, but looking for work",India,NaN,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,A lot more welcome now than last year,Tech articles written by other developers;Indu...,24.0,Man,No,Straight / Heterosexual,NaN,NaN,Appropriate in length,Neither easy nor difficult
9,10,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",NaN,...,Somewhat less welcome now than last year,Tech articles written by other developers;Tech...,NaN,NaN,NaN,NaN,NaN,Yes,Too long,Difficult
14,15,I am a student who is learning to code,Yes,Never,"OSS is, on average, of HIGHER quality than pro...","Not employed, but looking for work",India,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,20.0,Man,No,NaN,NaN,Yes,Too long,Neither easy nor difficult
49,50,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of LOWER quality than prop...",Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Another engineering discipline (ex. civil, ele...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Tech...,23.0,Man,No,NaN,South Asian,No,Too long,Easy
64,65,I am a developer by profession,Yes,Never,NaN,Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Information systems, information technology, o...",...,A lot more welcome now than last year,NaN,21.0,Man,No,NaN,NaN,Yes,Appropriate in length,Neither easy nor difficult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88808,77339,NaN,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)","Another engineering discipline (ex. civil, ele...",...,Not applicable - I did not use Stack Overflow ...,Tech articles written by other developers;Indu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88825,79795,NaN,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Somewhat more welcome now than last year,Tech meetups or events in your area;Courses on...,NaN,Man,No,Straight / Heterosexual,NaN,No,Too long,Difficult
88852,83862,NaN,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,24.0,Man,No,Straight / Heterosexual,NaN,Yes,Too long,Neither easy nor difficult
88853,84299,NaN,Yes,Never,The quality of OSS and closed source software ...,Employed full-time,India,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,...,Somewhat more welcome now than last year,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88864,86012,NaN,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Another engineering discipline (ex. civil, ele...",...,Not applicable - I did not use Stack Overflow ...,Industry news about technologies you're intere...,24.0,Man,No,NaN,South Asian,NaN,Appropriate in length,Easy

In [12]:
india.to_csv(r"india_python.csv")

# excel

In [ ]:
# this will install excel

In [4]:
pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\baps\anaconda3\lib\site-packages (3.0.10)
Requirement already satisfied: et_xmlfile in c:\users\baps\anaconda3\lib\site-packages (from openpyxl) (1.1.0)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
# for read excel

In [5]:
pip install xlrd

Collecting xlrd
  Downloading xlrd-2.0.1-py2.py3-none-any.whl (96 kB)
     -------------------------------------- 96.5/96.5 kB 918.0 kB/s eta 0:00:00
Installing collected packages: xlrd
Successfully installed xlrd-2.0.1
Note: you may need to restart the kernel to use updated packages.

In [ ]:
# for write excel

In [6]:
pip install xlwt

Collecting xlwt
  Downloading xlwt-1.3.0-py2.py3-none-any.whl (99 kB)
     -------------------------------------- 100.0/100.0 kB 1.9 MB/s eta 0:00:00
Installing collected packages: xlwt
Successfully installed xlwt-1.3.0
Note: you may need to restart the kernel to use updated packages.

In [7]:
sells = pd.read_excel(r"Dataset/Super Store Sales data.xls")
sells

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,Country,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,IN-2013-27828,2013-08-26,2013-08-30,Standard Class,VT-21700,Valerie Takahito,Home Office,Luoyang,Fujian,China,North Asia,OFF-PA-10000026,Office Supplies,Paper,"Eaton Cards & Envelopes, 8.5 x 11",197.280,4,0.00,35.400
1,2,IN-2013-27828,2013-08-26,2013-08-30,Standard Class,VT-21700,Valerie Takahito,Home Office,Luoyang,Fujian,China,North Asia,FUR-FU-10000944,Furniture,Furnishings,"Tenex Door Stop, Black",307.230,7,0.00,21.420
2,3,IN-2013-27828,2013-08-26,2013-08-30,Standard Class,VT-21700,Valerie Takahito,Home Office,Luoyang,Fujian,China,North Asia,TEC-CO-10002526,Technology,Copiers,"Sharp Wireless Fax, Digital",1422.240,4,0.00,526.200
3,4,IN-2013-27828,2013-08-26,2013-08-30,Standard Class,VT-21700,Valerie Takahito,Home Office,Luoyang,Fujian,China,North Asia,TEC-AC-10002255,Technology,Accessories,"Memorex Keyboard, Erganomic",207.450,3,0.00,78.750
4,5,IN-2014-63178,2014-06-24,2014-06-30,Standard Class,SO-20335,Sean O'Donnell,Consumer,Marikina,National Capital,Philippines,Southeast Asia,OFF-AP-10002882,Office Supplies,Appliances,"KitchenAid Coffee Grinder, Silver",121.074,2,0.15,37.014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10995,10996,IN-2013-82673,2013-09-10,2013-09-14,Standard Class,EM-13810,Eleni McCrary,Corporate,Wellington,Wellington,New Zealand,Oceania,OFF-ST-10004748,Office Supplies,Storage,"Smead Lockers, Blue",396.840,2,0.00,59.520
10996,10997,IN-2013-82673,2013-09-10,2013-09-14,Standard Class,EM-13810,Eleni McCrary,Corporate,Wellington,Wellington,New Zealand,Oceania,TEC-CO-10002678,Technology,Copiers,"Brother Wireless Fax, High-Speed",1508.040,4,0.00,437.280
10997,10998,IN-2013-82673,2013-09-10,2013-09-14,Standard Class,EM-13810,Eleni McCrary,Corporate,Wellington,Wellington,New Zealand,Oceania,OFF-LA-10000959,Office Supplies,Labels,"Harbour Creations Round Labels, Alphabetical",6.570,1,0.00,0.630
10998,10999,ID-2012-83604,2012-08-28,2012-08-28,Same Day,PO-19195,Phillina Ober,Home Office,Gold Coast,Queensland,Australia,Oceania,FUR-BO-10002866,Furniture,Bookcases,"Safco Classic Bookcase, Pine",1582.200,6,0.40,-870.300
10999,11000,ID-2012-83604,2012-08-28,2012-08-28,Same Day,PO-19195,Phillina Ober,Home Office,Gold Coast,Queensland,Australia,Oceania,OFF-LA-10000793,Office Supplies,Labels,"Harbour Creations Removable Labels, Laser Prin...",48.816,8,0.40,-6.624

In [8]:
China = sells[sells["Country"]=="China"]
China

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,Country,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,IN-2013-27828,2013-08-26,2013-08-30,Standard Class,VT-21700,Valerie Takahito,Home Office,Luoyang,Fujian,China,North Asia,OFF-PA-10000026,Office Supplies,Paper,"Eaton Cards & Envelopes, 8.5 x 11",197.280,4,0.0,35.400
1,2,IN-2013-27828,2013-08-26,2013-08-30,Standard Class,VT-21700,Valerie Takahito,Home Office,Luoyang,Fujian,China,North Asia,FUR-FU-10000944,Furniture,Furnishings,"Tenex Door Stop, Black",307.230,7,0.0,21.420
2,3,IN-2013-27828,2013-08-26,2013-08-30,Standard Class,VT-21700,Valerie Takahito,Home Office,Luoyang,Fujian,China,North Asia,TEC-CO-10002526,Technology,Copiers,"Sharp Wireless Fax, Digital",1422.240,4,0.0,526.200
3,4,IN-2013-27828,2013-08-26,2013-08-30,Standard Class,VT-21700,Valerie Takahito,Home Office,Luoyang,Fujian,China,North Asia,TEC-AC-10002255,Technology,Accessories,"Memorex Keyboard, Erganomic",207.450,3,0.0,78.750
22,23,ID-2014-64914,2014-03-27,2014-03-28,First Class,AS-10285,Alejandro Savely,Corporate,Kaiyuan,Liaoning,China,North Asia,FUR-TA-10000147,Furniture,Tables,"Lesro Coffee Table, Rectangular",1048.194,6,0.3,-284.526
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9972,9973,ID-2012-66111,2012-06-14,2012-06-17,First Class,AB-10015,Aaron Bergman,Consumer,Wuhan,Hubei,China,North Asia,TEC-MA-10003704,Technology,Machines,"StarTech Printer, Wireless",1024.680,8,0.5,-286.920
9984,9985,IN-2012-40813,2012-12-07,2012-12-11,Second Class,CA-11965,Carol Adams,Corporate,Foshan,Guangdong,China,North Asia,TEC-PH-10004085,Technology,Phones,"Apple Audio Dock, with Caller ID",166.890,1,0.0,38.370
9985,9986,IN-2012-40813,2012-12-07,2012-12-11,Second Class,CA-11965,Carol Adams,Corporate,Foshan,Guangdong,China,North Asia,OFF-ST-10004325,Office Supplies,Storage,"Eldon Box, Single Width",30.870,3,0.0,12.330
9986,9987,IN-2012-40813,2012-12-07,2012-12-11,Second Class,CA-11965,Carol Adams,Corporate,Foshan,Guangdong,China,North Asia,OFF-FA-10003530,Office Supplies,Fasteners,"OIC Clamps, Bulk Pack",59.310,3,0.0,14.760
9996,9997,IN-2011-33771,2011-06-28,2011-07-02,Standard Class,SC-20440,Shaun Chance,Corporate,Laiyang,Shandong,China,North Asia,FUR-CH-10003419,Furniture,Chairs,"Hon Steel Folding Chair, Black",78.990,1,0.0,11.040

In [13]:
China.to_excel(r"Dataset/china.xlsx")

# json

In [14]:
df = pd.read_csv(r"Dataset/survey_results_public.csv")

In [15]:
df.to_json(r"C:/Users/baps/OneDrive/Desktop/Coding_Cloud/2. Python libraries/file.json")

In [16]:
file = pd.read_json(r"C:/Users/baps/OneDrive/Desktop/Coding_Cloud/2. Python libraries/file.json")
file

,Respondent,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
0,1,I am a student who is learning to code,Yes,Never,The quality of OSS and closed source software ...,"Not employed, and not looking for work",United Kingdom,No,Primary/elementary school,None,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,14.0,Man,No,Straight / Heterosexual,None,No,Appropriate in length,Neither easy nor difficult
1,2,I am a student who is learning to code,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",Bosnia and Herzegovina,"Yes, full-time","Secondary school (e.g. American high school, G...",None,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,19.0,Man,No,Straight / Heterosexual,None,No,Appropriate in length,Neither easy nor difficult
2,3,"I am not primarily a developer, but I write co...",Yes,Never,The quality of OSS and closed source software ...,Employed full-time,Thailand,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,28.0,Man,No,Straight / Heterosexual,None,Yes,Appropriate in length,Neither easy nor difficult
3,4,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,United States,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,White or of European descent,No,Appropriate in length,Easy
4,5,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,Ukraine,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",...,Just as welcome now as I felt last year,Tech meetups or events in your area;Courses on...,30.0,Man,No,Straight / Heterosexual,White or of European descent;Multiracial,No,Appropriate in length,Easy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88878,88377,None,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,"Not employed, and not looking for work",Canada,No,Primary/elementary school,None,...,None,Tech articles written by other developers;Tech...,NaN,Man,No,None,None,No,Appropriate in length,Easy
88879,88601,None,No,Never,The quality of OSS and closed source software ...,None,None,None,None,None,...,None,None,NaN,None,None,None,None,None,None,None
88880,88802,None,No,Never,None,Employed full-time,None,None,None,None,...,None,None,NaN,None,None,None,None,None,None,None
88881,88816,None,No,Never,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",None,None,None,None,...,None,None,NaN,None,None,None,None,None,None,None
88882,88863,None,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, and not looking for work",Spain,"Yes, full-time","Professional degree (JD, MD, etc.)","Computer science, computer engineering, or sof...",...,Somewhat less welcome now than last year,Tech articles written by other developers;Indu...,18.0,Man,No,Straight / Heterosexual,Hispanic or Latino/Latina;White or of European...,No,Appropriate in length,Easy

In [17]:
df.to_json(r"C:/Users/baps/OneDrive/Desktop/Coding_Cloud/2. Python libraries/file1.json",orient="index")

In [18]:
file1 = pd.read_json(r"C:/Users/baps/OneDrive/Desktop/Coding_Cloud/2. Python libraries/file1.json")
file1

,0,1,2,3,4,5,6,7,8,9,...,88873,88874,88875,88876,88877,88878,88879,88880,88881,88882
Respondent,1,2,3,4,5,6,7,8,9,10,...,88062,88076,88182,88212,88282,88377,88601,88802,88816,88863
MainBranch,I am a student who is learning to code,I am a student who is learning to code,"I am not primarily a developer, but I write co...",I am a developer by profession,I am a developer by profession,"I am not primarily a developer, but I write co...",I am a developer by profession,I code primarily as a hobby,I am a developer by profession,I am a developer by profession,...,None,None,None,None,None,None,None,None,None,None
Hobbyist,Yes,No,Yes,No,Yes,Yes,No,Yes,Yes,Yes,...,No,No,Yes,No,Yes,Yes,No,No,No,Yes
OpenSourcer,Never,Less than once per year,Never,Never,Once a month or more often,Never,Never,Less than once per year,Once a month or more often,Once a month or more often,...,Never,Never,Once a month or more often,Less than once per year,Once a month or more often,Less than once a month but more than once per ...,Never,Never,Never,Less than once per year
OpenSource,The quality of OSS and closed source software ...,The quality of OSS and closed source software ...,The quality of OSS and closed source software ...,The quality of OSS and closed source software ...,"OSS is, on average, of HIGHER quality than pro...",The quality of OSS and closed source software ...,The quality of OSS and closed source software ...,"OSS is, on average, of HIGHER quality than pro...",The quality of OSS and closed source software ...,"OSS is, on average, of HIGHER quality than pro...",...,"OSS is, on average, of LOWER quality than prop...","OSS is, on average, of HIGHER quality than pro...","OSS is, on average, of HIGHER quality than pro...","OSS is, on average, of HIGHER quality than pro...",The quality of OSS and closed source software ...,The quality of OSS and closed source software ...,The quality of OSS and closed source software ...,None,"OSS is, on average, of HIGHER quality than pro...","OSS is, on average, of HIGHER quality than pro..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Sexuality,Straight / Heterosexual,Straight / Heterosexual,Straight / Heterosexual,Straight / Heterosexual,Straight / Heterosexual,Straight / Heterosexual,Straight / Heterosexual,Straight / Heterosexual,Bisexual,None,...,None,None,Straight / Heterosexual,Straight / Heterosexual,Straight / Heterosexual,None,None,None,None,Straight / Heterosexual
Ethnicity,None,None,None,White or of European descent,White or of European descent;Multiracial,East Asian,White or of European descent,None,White or of European descent,None,...,None,None,None,White or of European descent,None,None,None,None,None,Hispanic or Latino/Latina;White or of European...
Dependents,No,No,Yes,No,No,No,Yes,None,No,Yes,...,None,None,Yes,No,No,No,None,None,None,No
SurveyLength,Appropriate in length,Appropriate in length,Appropriate in length,Appropriate in length,Appropriate in length,Too long,Appropriate in length,Appropriate in length,Appropriate in length,Too long,...,None,None,Too short,Appropriate in length,Too short,Appropriate in length,None,None,None,Appropriate in length
SurveyEase,Neither easy nor difficult,Neither easy nor difficult,Neither easy nor difficult,Easy,Easy,Neither easy nor difficult,Neither easy nor difficult,Neither easy nor difficult,Neither easy nor difficult,Difficult,...,None,None,Neither easy nor difficult,Easy,Neither easy nor difficult,Easy,None,None,None,Easy

In [3]:
import pandas as pd
import os

df = (r"Dataset/survey_results_public.csv")

# Path to Downloads folder
df = os.path.expanduser(r"C:\Users\Dell\Downloads")

# Save file
df.to_csv(f"{df}/cleaned_file.csv", index=False)

AttributeError: 'str' object has no attribute 'to_csv'